name: base-workflow

on:
  workflow_dispatch:

env:
    name: hi there

jobs:
  testings:
    runs-on: ubuntu-latest

    env:
        password: check

    steps:
      - uses: actions/checkout@v4
      

      - name: "Checking if this working"
        run: echo "$name Abhishek"
