name: base-workflow

on:
  workflow_dispatch:

jobs:
  testings:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Checking if this working"
        run: echo "hi there"
